import type { Metadata } from "next";
import "./globals.css";
import { PortfolioProvider } from "../app/context/PortfolioContext";
export const metadata: Metadata = {
  title: "Akeem lanre-Abass Portfolio",
  description: "Generated by Akeem lanre-Abass",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PortfolioProvider>{children}</PortfolioProvider>
      </body>
    </html>
  );
}
