import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Akeem lanre-Abass Portfolio",
  description: "Generated by Akeem lanre-Abass",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       
      >
        {children}
      </body>
    </html>
  );
}
